# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 575)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.outputLabel = QtWidgets.QLabel(self.centralwidget)
        self.outputLabel.setGeometry(QtCore.QRect(10, 10, 331, 81))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.outputLabel.setFont(font)
        self.outputLabel.setFrameShape(QtWidgets.QFrame.Box)
        self.outputLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.outputLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.outputLabel.setObjectName("outputLabel")
        self.percentButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.percent_it())
        self.percentButton.setGeometry(QtCore.QRect(5, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.percentButton.setFont(font)
        self.percentButton.setObjectName("percentButton")
        self.cButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("C"))
        self.cButton.setGeometry(QtCore.QRect(90, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.cButton.setFont(font)
        self.cButton.setObjectName("cButton")
        self.delButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.remove_it())
        self.delButton.setGeometry(QtCore.QRect(180, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.delButton.setFont(font)
        self.delButton.setObjectName("delButton")
        self.divideButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("/"))
        self.divideButton.setGeometry(QtCore.QRect(270, 100, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divideButton.setFont(font)
        self.divideButton.setObjectName("divideButton")
        self.threeButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("3"))
        self.threeButton.setGeometry(QtCore.QRect(180, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.threeButton.setFont(font)
        self.threeButton.setObjectName("threeButton")
        self.twoButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("2"))
        self.twoButton.setGeometry(QtCore.QRect(90, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.twoButton.setFont(font)
        self.twoButton.setObjectName("twoButton")
        self.oneButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("1"))
        self.oneButton.setGeometry(QtCore.QRect(5, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.oneButton.setFont(font)
        self.oneButton.setObjectName("oneButton")
        self.multiplyButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("*"))
        self.multiplyButton.setGeometry(QtCore.QRect(270, 180, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.multiplyButton.setFont(font)
        self.multiplyButton.setObjectName("multiplyButton")
        self.sixButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("6"))
        self.sixButton.setGeometry(QtCore.QRect(180, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sixButton.setFont(font)
        self.sixButton.setObjectName("sixButton")
        self.fiveButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("5"))
        self.fiveButton.setGeometry(QtCore.QRect(90, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fiveButton.setFont(font)
        self.fiveButton.setObjectName("fiveButton")
        self.fourButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("4"))
        self.fourButton.setGeometry(QtCore.QRect(5, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.fourButton.setFont(font)
        self.fourButton.setObjectName("fourButton")
        self.addButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("+"))
        self.addButton.setGeometry(QtCore.QRect(270, 270, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.nineButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("9"))
        self.nineButton.setGeometry(QtCore.QRect(180, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.nineButton.setFont(font)
        self.nineButton.setObjectName("nineButton")
        self.eightButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("8"))
        self.eightButton.setGeometry(QtCore.QRect(90, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.eightButton.setFont(font)
        self.eightButton.setObjectName("eightButton")
        self.sevenButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("7"))
        self.sevenButton.setGeometry(QtCore.QRect(5, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.sevenButton.setFont(font)
        self.sevenButton.setObjectName("sevenButton")
        self.subtractButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("-"))
        self.subtractButton.setGeometry(QtCore.QRect(270, 360, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.subtractButton.setFont(font)
        self.subtractButton.setObjectName("subtractButton")
        self.equalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.math_it())
        self.equalButton.setGeometry(QtCore.QRect(270, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.equalButton.setFont(font)
        self.equalButton.setObjectName("equalButton")
        self.oppoButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.opposite_it())
        self.oppoButton.setGeometry(QtCore.QRect(5, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.oppoButton.setFont(font)
        self.oppoButton.setObjectName("oppoButton")
        self.decimalButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.dot_it())
        self.decimalButton.setGeometry(QtCore.QRect(180, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimalButton.setFont(font)
        self.decimalButton.setObjectName("decimalButton")
        self.zeroButton = QtWidgets.QPushButton(self.centralwidget, clicked= lambda:self.pressed_it("0"))
        self.zeroButton.setGeometry(QtCore.QRect(90, 450, 75, 75))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.zeroButton.setFont(font)
        self.zeroButton.setObjectName("zeroButton")
        self.tempLabel = QtWidgets.QLabel(self.centralwidget)
        self.tempLabel.setGeometry(QtCore.QRect(10, 10, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tempLabel.setFont(font)
        self.tempLabel.setText("")
        self.tempLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tempLabel.setObjectName("tempLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def percent_it(self):
        screen = self.outputLabel.text()
        answer = (eval(screen) / 100)
        self.outputLabel.setText(str(answer))
    
    def math_it(self):
        screen = self.tempLabel.text() + self.outputLabel.text() 
        try:
            answer = eval(screen)
            self.outputLabel.setText(str(answer))
            self.tempLabel.setText("")
        except:
            self.outputLabel.setText("ERROR")
    
    def opposite_it(self):
        screen = self.outputLabel.text()
        if "-" in screen:
            self.outputLabel.setText(screen.replace("-",""))
        else:
            self.outputLabel.setText(f'-{screen}')
    
    def remove_it(self):
        screen = self.outputLabel.text()
        screen = screen[:-1]
        self.outputLabel.setText(screen)
    
    def dot_it(self):
        global dot 
        dot = False
        if dot == False:
            self.outputLabel.setText(f'{self.outputLabel.text()}{"."}')
            dot == True
    
    def pressed_it(self, pressed):
        if pressed == "C":
            self.outputLabel.setText("0")
            self.tempLabel.setText("")
        else:
            if pressed == "+":
                self.tempLabel.setText(f'{self.tempLabel.text()}{self.outputLabel.text()}{pressed}')
                self.outputLabel.setText("")
                dot = False
            elif pressed == "-":
                self.tempLabel.setText(f'{self.tempLabel.text()}{self.outputLabel.text()}{pressed}')
                self.outputLabel.setText("")
                dot = False
            elif pressed == "*":
                self.tempLabel.setText(f'{self.tempLabel.text()}{self.outputLabel.text()}{pressed}')
                self.outputLabel.setText("")
                dot = False
            elif pressed == "/":
                self.tempLabel.setText(f'{self.tempLabel.text()}{self.outputLabel.text()}{pressed}')
                self.outputLabel.setText("")
                dot = False
            else:
                if self.outputLabel.text() == "0":
                    self.outputLabel.setText("")
                self.outputLabel.setText(f' {self.outputLabel.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.outputLabel.setText(_translate("MainWindow", "0"))
        self.percentButton.setText(_translate("MainWindow", "%"))
        self.cButton.setText(_translate("MainWindow", "C"))
        self.delButton.setText(_translate("MainWindow", "<<"))
        self.divideButton.setText(_translate("MainWindow", "/"))
        self.threeButton.setText(_translate("MainWindow", "3"))
        self.twoButton.setText(_translate("MainWindow", "2"))
        self.oneButton.setText(_translate("MainWindow", "1"))
        self.multiplyButton.setText(_translate("MainWindow", "*"))
        self.sixButton.setText(_translate("MainWindow", "6"))
        self.fiveButton.setText(_translate("MainWindow", "5"))
        self.fourButton.setText(_translate("MainWindow", "4"))
        self.addButton.setText(_translate("MainWindow", "+"))
        self.nineButton.setText(_translate("MainWindow", "9"))
        self.eightButton.setText(_translate("MainWindow", "8"))
        self.sevenButton.setText(_translate("MainWindow", "7"))
        self.subtractButton.setText(_translate("MainWindow", "-"))
        self.equalButton.setText(_translate("MainWindow", "="))
        self.oppoButton.setText(_translate("MainWindow", "+/-"))
        self.decimalButton.setText(_translate("MainWindow", "."))
        self.zeroButton.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
